### ISSUE TITLE
Project 'core' could not be found in workspace.

### ISSUE THREAD

**Issue by Crazycolorz5** [graycoreio/daffodil#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Upon following the instructions in  the README.md, errors occur on the `ng build core` step. The error is:
```
Error: Project 'core' could not be found in workspace.    at Workspace.getProject (/home/crazycolorz5/Documents/daffodil-test/node_modules/@angular-devkit/core/src/workspace/workspace.js:83:19)
    at Architect.getBuilderConfiguration (/home/crazycolorz5/Documents/daffodil-test/node_modules/@angular-devkit/architect/src/architect.js:96:41)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/home/crazycolorz5/Documents/daffodil-test/node_modules/@angular/cli/models/architect-command.js:64:55)
    at MergeMapSubscriber._tryNext (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/home/crazycolorz5/Documents/daffodil-test/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
```

## Expected behavior

A build is successful and I am able to run a small demo.

## Minimal reproduction of the problem with instructions

Follow the instructions in the README.md

## What is the motivation / use case for changing the behavior?

Make setup easier.

## Environment
I installed npm from the Arch Linux repos, and did `sudo npm install -g @angular/cli` followed by `ng new daffodil-test`. Other than that I followed the instructions in the README.md.

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: 10.4.1 
- Platform:  Antergos (Distribution of Arch Linux) 

Others:

</code></pre>

**Comment by Crazycolorz5** [comment]
The instruction to add to the default AppModule is slightly confusing. I am assuming that is referring to the file `./app/app.module.ts`?

**Comment by damienwebdev** [comment]
@Crazycolorz5 To your question about `AppModule`, Yep. 

There's two things happening:

1. We're working on getting schematics which will make project installation much easier. Currently, we're still in a super-alpha phase of development, but thanks for trying to get it set up.

2. Currently the published npm module is super out of date. We're waiting to publish a release until we get out of super-alpha. 

I'm going to leave this issue open until we've hit that point.

**Comment by griest024** [comment]
Is this still relevant? Are we going to write some Angular schematics?

**Comment by damienwebdev** [comment]
@griest024 I think so. The original issue here is more related to an attempt to use the project in the first place -- which is still a less than stellar process from a docs and ergonomics perspective. Schematics would make it easier, but I don't know if we're ready to commit to creating schematics yet while the APIs are still considered unstable.  

I've left this issue open for a while as a goal to remind myself of the early days where we can target a real "new" user, @Crazycolorz5 attempt to try the framework for the very first time.

**Comment by damienwebdev** [comment]
Hi @Crazycolorz5! It has been a very long time, I hope you are well. If you have a few minutes of downtime, would you mind running through https://next.daff.io/docs/guides/getting-started and giving it a try? If you wind up with a successful demo, can you close this issue?

**Comment by Crazycolorz5** [comment]
I am confirming that the setup instructions function for me.
